package com.jobseekercopilot.applicationtracker.entity;

public enum ApplicationEventType {
    LEGACY_SNAPSHOT,
    APPLICATION_CREATED,
    STATUS_CHANGED,
    DOCUMENT_REFERENCE_CHANGED,
    DOCUMENT_REFERENCES_RECONCILED,
    GENERATED_APPLICATION_WITHDRAWN,
    APPLICATION_DELETED
}
